# Generated by Django 5.0.4 on 2024-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_educationalorganizationmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Нефтегазовая', 'Нефтегазовая'), ('Офисная', 'Офисная')], max_length=255),
        ),
        migrations.AddField(
            model_name='subdivisionmodel',
            name='department',
            field=models.CharField(blank=True, choices=[('ГСП', 'Газтройпром'), ('ГСП 2', 'ГСП2')], max_length=255),
        ),
    ]
